### ISSUE TITLE
AnimeScrapper errors

### ISSUE THREAD

**Issue by H4AED** [jafriyie1/goanime#2]
First of all, thanks for your contribution. This will help me tremendously in learning Go, as I'm quite new.

I have found some errors in your code:

```
`C:\Users\H4AED\go\src\github.com\jafriyie1\goanime\cmd\goanime>go run main.go

.\main.go:52:74: too many arguments in call to animescrapper.GetRangeOfEpisodes
        have (bool)
        want ()
.\main.go:57:74: too many arguments in call to animescrapper.GetRangeOfEpisodes
        have (bool)
        want ()
.\main.go:72:35: not enough arguments in call to animescrapper.ConcurrentEpisodes
        have (string, string, string, string, *chromedp.CDP, context.Context)
        want (string, string, string, string, *sync.WaitGroup, *chromedp.CDP, context.Context)`
```

**Comment by jafriyie1** [comment]
Hi thank you so much for looking at this project! I'm also quite new to Go so there is still plenty for me to learn. I accidentally pushed the wrong version of the animescrapper file. I just made the new changes. Let me know if that fixes the issue.

**Comment by jafriyie1** [comment]
I'm going to close out this issue since I made that fix. Let me know if you run into any more issues
